# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2023-01-13 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementlevels',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
