version: "3"
services: 
  django-apache2:
    build: .
    container_name: dlc-placement
    env_file:
      - ./.env
    ports:
      - '8005:80'
      - '3501:3500'
      - '4701:81'
    command: bash -c "./startup.sh"