# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2021-07-07 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoresheetView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sid', models.CharField(blank=True, default='', max_length=16)),
                ('first_name', models.CharField(blank=True, default='', max_length=32)),
                ('last_name', models.CharField(blank=True, default='', max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('comments', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('user_id', models.IntegerField()),
                ('cas_user', models.CharField(max_length=255)),
                ('level_id', models.IntegerField()),
                ('level', models.CharField(max_length=500)),
                ('exam_date', models.DateField()),
                ('language_id', models.IntegerField()),
                ('language_name', models.CharField(max_length=255, null=True)),
                ('needs_review', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'scoresheets_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scoresheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sid', models.CharField(blank=True, default='', max_length=16)),
                ('first_name', models.CharField(blank=True, default='', max_length=32)),
                ('last_name', models.CharField(blank=True, default='', max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('comments', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('tester_id', models.IntegerField()),
                ('exam_date', models.DateField()),
                ('language_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement_level_id', models.IntegerField()),
                ('needs_review', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'scoresheets',
                'managed': True,
            },
        ),
    ]
