# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2021-07-07 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LanguagesUsersView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('language_id', models.IntegerField()),
                ('language_name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'languages_users_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LanguagesUsers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('language_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'languages_users',
                'managed': True,
            },
        ),
    ]
